### ISSUE TITLE
Vaadin Testbench + Dropwizard App Rule

### ISSUE THREAD

**Issue by scho** [jangalinski/dropwizard-vaadin#1]
Hi,

I started a playground project in order to try out Dropwizard together with Vaadin. All our services use Dropwizard, so I thought why not using it for the Vaadin projects.

Your `VaadinBundle` works perfectly thanks for that! What I couldn't figure out though, is how to use the Vaadin Testbench together with the Dropwizard App Rule. The Browser starts and everything seems to work, but the Servlet that is supposed to serve the Vaadin stuff is somehow not there. All works find when I start the Dropwizard server by hand.

I also get a warning on startup, which seems to be related to a javax servlet version issue (at least google indicates that):
```
WARN  [2015-04-19 07:59:15,204] org.eclipse.jetty.servlet.ServletHandler: Error for /test
! java.lang.NoSuchMethodError: javax.servlet.http.HttpServletResponse.getHeader(Ljava/lang/String;)Ljava/lang/String;
! at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:322) ~[jetty-servlets-9.2.9.v20150224.jar:9.2.9.v20150224]
! at io.dropwizard.jetty.BiDiGzipFilter.doFilter(BiDiGzipFilter.java:134) ~[dropwizard-jetty-0.8.1.jar:0.8.1]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) ~[jetty-servlet-9.2.9.v20150224.jar:9.2.9.v20150224]
! at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:29) ~[dropwizard-servlets-0.8.1.jar:0.8.1]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) ~[jetty-servlet-9.2.9.v20150224.jar:9.2.9.v20150224]
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:44) ~[dropwizard-jersey-0.8.1.jar:0.8.1]
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:39) ~[dropwizard-jersey-0.8.1.jar:0.8.1]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) ~[jetty-servlet-9.2.9.v20150224.jar:9.2.9.v20150224]
! at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119) ~[guice-servlet-4.0-beta5.jar:na]
! at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133) ~[guice-servlet-4.0-beta5.jar:na]
! at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130) ~[guice-servlet-4.0-beta5.jar:na]
! at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203) ~[guice-servlet-4.0-beta5.jar:na]
! at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130) ~[guice-servlet-4.0-beta5.jar:na]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) ~[jetty-servlet-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [jetty-servlet-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:240) [metrics-jetty9-3.1.1.jar:3.1.1]
! at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:51) [dropwizard-jetty-0.8.1.jar:0.8.1]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:95) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:159) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.Server.handle(Server.java:497) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [jetty-server-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-io-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-util-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-util-9.2.9.v20150224.jar:9.2.9.v20150224]
! at java.lang.Thread.run(Thread.java:745) [na:1.8.0_20]
```

Do you have any clue why this is happening?

**Comment by scho** [comment]
Btw, this is the dependency tree from maven:
```
[INFO] +- io.dropwizard:dropwizard-assets:jar:0.8.1:compile
[INFO] |  \- io.dropwizard:dropwizard-servlets:jar:0.8.1:compile
[INFO] |     \- io.dropwizard.metrics:metrics-annotation:jar:3.1.1:compile
[INFO] +- com.github.fakemongo:fongo:jar:1.6.2:compile
[INFO] |  +- rhino:js:jar:1.7R2:compile
[INFO] |  +- com.vividsolutions:jts:jar:1.13:compile
[INFO] |  \- de.grundid.opendatalab:geojson-jackson:jar:1.2:compile
[INFO] +- com.vaadin:vaadin-themes:jar:7.4.3:compile
[INFO] +- com.vaadin:vaadin-client-compiled:jar:7.4.3:compile
[INFO] +- com.vaadin:vaadin-server:jar:7.4.3:compile
[INFO] |  +- com.vaadin:vaadin-sass-compiler:jar:0.9.12:compile
[INFO] |  |  +- org.w3c.css:sac:jar:1.3:compile
[INFO] |  |  \- com.vaadin.external.flute:flute:jar:1.3.0.gg2:compile
[INFO] |  +- com.vaadin:vaadin-shared:jar:7.4.3:compile
[INFO] |  |  +- com.vaadin.external.streamhtmlparser:streamhtmlparser-jsilver:jar:0.0.10.vaadin1:compile
[INFO] |  |  \- com.vaadin.external.google:guava:jar:16.0.1.vaadin1:compile
[INFO] |  \- org.jsoup:jsoup:jar:1.8.1:compile
[INFO] +- com.vaadin:vaadin-testbench:jar:4.0.2:test
[INFO] |  +- com.vaadin:vaadin-testbench-core:jar:4.0.2:test
[INFO] |  |  +- org.seleniumhq.selenium:selenium-server:jar:2.44.0:test
[INFO] |  |  |  +- org.bouncycastle:bcprov-jdk15on:jar:1.48:test
[INFO] |  |  |  +- org.bouncycastle:bcpkix-jdk15on:jar:1.48:test
[INFO] |  |  |  +- mx4j:mx4j-tools:jar:3.0.1:test
[INFO] |  |  |  +- org.mortbay.jetty:servlet-api-2.5:jar:6.1.9:test
[INFO] |  |  |  +- org.seleniumhq.selenium:jetty-repacked:jar:7.6.1:test
[INFO] |  |  |  +- org.seleniumhq.selenium:jetty-rc-repacked:jar:5:test
[INFO] |  |  |  +- net.jcip:jcip-annotations:jar:1.0:test
[INFO] |  |  |  \- org.yaml:snakeyaml:jar:1.8:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-remote-driver:jar:2.44.0:test
[INFO] |  |  |  +- cglib:cglib-nodep:jar:2.1_3:test
[INFO] |  |  |  +- com.google.code.gson:gson:jar:2.3:test
[INFO] |  |  |  +- org.seleniumhq.selenium:selenium-api:jar:2.44.0:test
[INFO] |  |  |  +- org.apache.commons:commons-exec:jar:1.1:test
[INFO] |  |  |  +- net.java.dev.jna:jna:jar:3.4.0:compile
[INFO] |  |  |  \- net.java.dev.jna:platform:jar:3.4.0:test
[INFO] |  |  +- org.seleniumhq.selenium:selenium-java:jar:2.44.0:test
[INFO] |  |  |  +- org.seleniumhq.selenium:selenium-chrome-driver:jar:2.44.0:test
[INFO] |  |  |  +- org.seleniumhq.selenium:selenium-htmlunit-driver:jar:2.44.0:test
[INFO] |  |  |  |  \- net.sourceforge.htmlunit:htmlunit:jar:2.15:test
[INFO] |  |  |  |     +- xalan:xalan:jar:2.7.1:test
[INFO] |  |  |  |     |  \- xalan:serializer:jar:2.7.1:test
[INFO] |  |  |  |     +- commons-collections:commons-collections:jar:3.2.1:test
[INFO] |  |  |  |     +- org.apache.httpcomponents:httpmime:jar:4.3.3:test
[INFO] |  |  |  |     +- net.sourceforge.htmlunit:htmlunit-core-js:jar:2.15:test
[INFO] |  |  |  |     +- xerces:xercesImpl:jar:2.11.0:test
[INFO] |  |  |  |     |  \- xml-apis:xml-apis:jar:1.4.01:test
[INFO] |  |  |  |     +- net.sourceforge.nekohtml:nekohtml:jar:1.9.21:test
[INFO] |  |  |  |     +- net.sourceforge.cssparser:cssparser:jar:0.9.14:test
[INFO] |  |  |  |     \- org.eclipse.jetty:jetty-websocket:jar:8.1.15.v20140411:test
[INFO] |  |  |  +- org.seleniumhq.selenium:selenium-firefox-driver:jar:2.44.0:test
[INFO] |  |  |  +- org.seleniumhq.selenium:selenium-ie-driver:jar:2.44.0:test
[INFO] |  |  |  +- org.seleniumhq.selenium:selenium-safari-driver:jar:2.44.0:test
[INFO] |  |  |  +- org.seleniumhq.selenium:selenium-support:jar:2.44.0:test
[INFO] |  |  |  \- org.webbitserver:webbit:jar:0.4.14:test
[INFO] |  |  |     \- io.netty:netty:jar:3.5.2.Final:test
[INFO] |  |  +- com.codeborne:phantomjsdriver:jar:1.2.1:test
[INFO] |  |  +- org.easymock:easymock:jar:3.1:test
[INFO] |  |  \- org.javassist:javassist:jar:3.18.1-GA:compile
[INFO] |  \- com.vaadin:vaadin-testbench-api:jar:7.4.0:test
[INFO] +- io.dropwizard:dropwizard-core:jar:0.8.1:compile
[INFO] |  +- io.dropwizard:dropwizard-util:jar:0.8.1:compile
[INFO] |  |  +- com.google.code.findbugs:jsr305:jar:3.0.0:compile
[INFO] |  |  \- joda-time:joda-time:jar:2.7:compile
[INFO] |  +- io.dropwizard:dropwizard-validation:jar:0.8.1:compile
[INFO] |  |  +- org.hibernate:hibernate-validator:jar:5.1.3.Final:compile
[INFO] |  |  |  +- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO] |  |  |  +- org.jboss.logging:jboss-logging:jar:3.1.3.GA:compile
[INFO] |  |  |  \- com.fasterxml:classmate:jar:1.0.0:compile
[INFO] |  |  \- org.glassfish:javax.el:jar:3.0.0:compile
[INFO] |  +- io.dropwizard:dropwizard-configuration:jar:0.8.1:compile
[INFO] |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.5.1:compile
[INFO] |  |  \- org.apache.commons:commons-lang3:jar:3.3.2:compile
[INFO] |  +- io.dropwizard:dropwizard-logging:jar:0.8.1:compile
[INFO] |  |  +- io.dropwizard.metrics:metrics-logback:jar:3.1.1:compile
[INFO] |  |  +- org.slf4j:jul-to-slf4j:jar:1.7.10:compile
[INFO] |  |  +- ch.qos.logback:logback-core:jar:1.1.2:compile
[INFO] |  |  +- org.slf4j:log4j-over-slf4j:jar:1.7.10:compile
[INFO] |  |  +- org.slf4j:jcl-over-slf4j:jar:1.7.10:compile
[INFO] |  |  \- org.eclipse.jetty:jetty-util:jar:9.2.9.v20150224:compile
[INFO] |  +- io.dropwizard:dropwizard-metrics:jar:0.8.1:compile
[INFO] |  +- io.dropwizard:dropwizard-jersey:jar:0.8.1:compile
[INFO] |  |  +- org.glassfish.jersey.core:jersey-server:jar:2.17:compile
[INFO] |  |  |  +- org.glassfish.jersey.media:jersey-media-jaxb:jar:2.17:compile
[INFO] |  |  |  \- javax.annotation:javax.annotation-api:jar:1.2:compile
[INFO] |  |  +- org.glassfish.jersey.ext:jersey-metainf-services:jar:2.17:compile
[INFO] |  |  +- io.dropwizard.metrics:metrics-jersey2:jar:3.1.1:compile
[INFO] |  |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.5.1:compile
[INFO] |  |  |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.5.1:compile
[INFO] |  |  |  \- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.5.1:compile
[INFO] |  |  +- org.glassfish.jersey.containers:jersey-container-servlet:jar:2.17:compile
[INFO] |  |  |  \- org.glassfish.jersey.containers:jersey-container-servlet-core:jar:2.17:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-server:jar:9.2.9.v20150224:compile
[INFO] |  |  |  +- javax.servlet:javax.servlet-api:jar:3.1.0:compile
[INFO] |  |  |  \- org.eclipse.jetty:jetty-io:jar:9.2.9.v20150224:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-webapp:jar:9.2.9.v20150224:compile
[INFO] |  |  |  \- org.eclipse.jetty:jetty-xml:jar:9.2.9.v20150224:compile
[INFO] |  |  \- org.eclipse.jetty:jetty-continuation:jar:9.2.9.v20150224:compile
[INFO] |  +- io.dropwizard:dropwizard-jetty:jar:0.8.1:compile
[INFO] |  |  +- io.dropwizard.metrics:metrics-jetty9:jar:3.1.1:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-servlet:jar:9.2.9.v20150224:compile
[INFO] |  |  |  \- org.eclipse.jetty:jetty-security:jar:9.2.9.v20150224:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-servlets:jar:9.2.9.v20150224:compile
[INFO] |  |  \- org.eclipse.jetty:jetty-http:jar:9.2.9.v20150224:compile
[INFO] |  +- io.dropwizard:dropwizard-lifecycle:jar:0.8.1:compile
[INFO] |  +- io.dropwizard.metrics:metrics-core:jar:3.1.1:compile
[INFO] |  +- io.dropwizard.metrics:metrics-jvm:jar:3.1.1:compile
[INFO] |  +- io.dropwizard.metrics:metrics-servlets:jar:3.1.1:compile
[INFO] |  |  \- io.dropwizard.metrics:metrics-json:jar:3.1.1:compile
[INFO] |  +- io.dropwizard.metrics:metrics-healthchecks:jar:3.1.1:compile
[INFO] |  +- net.sourceforge.argparse4j:argparse4j:jar:0.4.4:compile
[INFO] |  \- org.eclipse.jetty.toolchain.setuid:jetty-setuid-java:jar:1.0.2:compile
[INFO] +- io.dropwizard:dropwizard-jackson:jar:0.8.1:compile
[INFO] |  +- com.google.guava:guava:jar:18.0:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-core:jar:2.5.1:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.5.1:compile
[INFO] |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk7:jar:2.5.1:compile
[INFO] |  +- com.fasterxml.jackson.datatype:jackson-datatype-guava:jar:2.5.1:compile
[INFO] |  +- com.fasterxml.jackson.module:jackson-module-afterburner:jar:2.5.1:compile
[INFO] |  +- com.fasterxml.jackson.datatype:jackson-datatype-joda:jar:2.5.1:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.10:compile
[INFO] |  \- ch.qos.logback:logback-classic:jar:1.1.2:compile
[INFO] +- io.dropwizard:dropwizard-auth:jar:0.8.1:compile
[INFO] +- io.dropwizard:dropwizard-client:jar:0.8.1:compile
[INFO] |  +- org.glassfish.jersey.core:jersey-client:jar:2.17:compile
[INFO] |  |  +- javax.ws.rs:javax.ws.rs-api:jar:2.0.1:compile
[INFO] |  |  +- org.glassfish.jersey.core:jersey-common:jar:2.17:compile
[INFO] |  |  |  +- org.glassfish.jersey.bundles.repackaged:jersey-guava:jar:2.17:compile
[INFO] |  |  |  \- org.glassfish.hk2:osgi-resource-locator:jar:1.0.1:compile
[INFO] |  |  +- org.glassfish.hk2:hk2-api:jar:2.4.0-b10:compile
[INFO] |  |  |  +- org.glassfish.hk2:hk2-utils:jar:2.4.0-b10:compile
[INFO] |  |  |  \- org.glassfish.hk2.external:aopalliance-repackaged:jar:2.4.0-b10:compile
[INFO] |  |  +- org.glassfish.hk2.external:javax.inject:jar:2.4.0-b10:compile
[INFO] |  |  \- org.glassfish.hk2:hk2-locator:jar:2.4.0-b10:compile
[INFO] |  +- io.dropwizard.metrics:metrics-httpclient:jar:3.1.1:compile
[INFO] |  \- org.glassfish.jersey.connectors:jersey-apache-connector:jar:2.17:compile
[INFO] +- com.hubspot.dropwizard:dropwizard-guice:jar:0.8.0:compile
[INFO] |  +- com.google.inject:guice:jar:4.0-beta5:compile
[INFO] |  +- com.google.inject.extensions:guice-servlet:jar:4.0-beta5:compile
[INFO] |  +- com.squarespace.jersey2-guice:jersey2-guice:jar:0.5:compile
[INFO] |  |  \- com.google.inject.extensions:guice-multibindings:jar:4.0-beta5:compile
[INFO] |  \- org.reflections:reflections:jar:0.9.9:compile
[INFO] +- io.dropwizard.modules:dropwizard-java8:jar:0.8.0-2:compile
[INFO] |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.5.1:compile
[INFO] |  \- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.5.1:compile
[INFO] +- org.mongodb:mongo-java-driver:jar:2.13.0:compile
[INFO] +- org.mongojack:mongojack:jar:2.3.0:compile
[INFO] |  +- de.undercouch:bson4jackson:jar:2.4.0:compile
[INFO] |  +- javax.persistence:persistence-api:jar:1.0.2:compile
[INFO] |  \- de.flapdoodle.embed:de.flapdoodle.embed.mongo:jar:1.46.4:compile
[INFO] |     \- de.flapdoodle.embed:de.flapdoodle.embed.process:jar:1.40.1:compile
[INFO] |        +- net.java.dev.jna:jna-platform:jar:4.0.0:compile
[INFO] |        \- org.apache.commons:commons-compress:jar:1.3:compile
[INFO] +- junit:junit:jar:4.12:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- org.hamcrest:hamcrest-library:jar:1.3:test
[INFO] +- com.github.tomakehurst:wiremock:jar:1.54:test
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.3.5:compile
[INFO] |  |  +- org.apache.httpcomponents:httpcore:jar:4.3.2:compile
[INFO] |  |  +- commons-logging:commons-logging:jar:1.1.3:compile
[INFO] |  |  \- commons-codec:commons-codec:jar:1.6:compile
[INFO] |  +- xmlunit:xmlunit:jar:1.5:test
[INFO] |  +- org.mortbay.jetty:jetty:jar:6.1.26:test
[INFO] |  |  +- org.mortbay.jetty:jetty-util:jar:6.1.26:test
[INFO] |  |  \- org.mortbay.jetty:servlet-api:jar:2.5-20081211:test
[INFO] |  +- org.skyscreamer:jsonassert:jar:1.2.3:test
[INFO] |  |  \- org.json:json:jar:20090211:test
[INFO] |  +- com.jayway.jsonpath:json-path:jar:0.8.1:test
[INFO] |  |  +- net.minidev:json-smart:jar:1.1.1:test
[INFO] |  |  \- commons-lang:commons-lang:jar:2.6:test
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.5.1:compile
[INFO] |  \- net.sf.jopt-simple:jopt-simple:jar:4.7:test
[INFO] \- io.dropwizard:dropwizard-testing:jar:0.8.1:test
[INFO]    +- org.mockito:mockito-core:jar:1.10.17:test
[INFO]    +- org.objenesis:objenesis:jar:2.1:test
[INFO]    +- org.assertj:assertj-core:jar:2.0.0:test
[INFO]    |  \- com.github.marschall:memoryfilesystem:jar:0.6.4:test
[INFO]    \- org.glassfish.jersey.test-framework.providers:jersey-test-framework-provider-inmemory:jar:2.17:test
[INFO]       +- org.glassfish.jersey.test-framework:jersey-test-framework-core:jar:2.17:test
[INFO]       \- org.ow2.asm:asm-debug-all:jar:5.0.2:test
```

**Comment by jangalinski** [comment]
I am not using vaadin testbench, so I cannot reproduce the problem. Maybe its best to ask on the dropwizard mailing list if someone has solved this already? Feel free to point to this repo, I'd happily accept any pull requests solving this issue.

**Comment by scho** [comment]
Thanks for your quick reply. I've just figured it out. You have to add explicitly a dependency to the `javax.servlet-api`. That did the trick :)
```
<dependency>
  <groupId>javax.servlet</groupId>
  <artifactId>javax.servlet-api</artifactId>
  <version>3.1.0</version>
  <scope>provided</scope>
</dependency>
```
As far as I see it, `selenium-server` adds a dependency to `javax.servlet-api` version `2.5`, that's why this is needed.
